<a href="https://colab.research.google.com/github/zoybathecodess/Digital-Reputation-Score-for-Small-Businesses/blob/main/amazon_reviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cleaned_data.csv')

In [ ]:
df_cleaned = df.head(200)
df_cleaned

,Unnamed: 0,product_id,rating,review_text
0,0,B001E4KFG0,5,I have bought several of the Vitality canned d...
1,1,B00813GRG4,1,Product arrived labeled as Jumbo Salted Peanut...
2,2,B000LQOCH0,4,This is a confection that has been around a fe...
3,3,B000UA0QIQ,2,If you are looking for the secret ingredient i...
4,4,B006K2ZZ7K,5,Great taffy at a great price. There was a wid...
...,...,...,...,...
195,195,B0028C44Z0,5,These little tins of sugar free mine mints wer...
196,196,B0028C44Z0,5,"Pros:<br />+packaging, shipping, price<br />+s..."
197,197,B0028C44Z0,3,Be careful not to eat too many of them in one ...
198,198,B0028C44Z0,5,These mints are really strong and have a great...
199,199,B0028C44Z0,5,This is a huge supply of them. I'm still worki...

In [ ]:
pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.1.4)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 8.7 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [ ]:
 analyzer = SentimentIntensityAnalyzer()

In [ ]:
def get_sentiment_score(text):
    score = analyzer.polarity_scores(text)
    return score['compound']

In [ ]:
df_cleaned.loc[:, 'sentiment_score'] = df_cleaned['review_text'].apply(get_sentiment_score)

In [ ]:
df2 = df_cleaned.copy().tail()

In [ ]:
df2

,Unnamed: 0,product_id,rating,review_text,sentiment_score
195,195,B0028C44Z0,5,These little tins of sugar free mine mints wer...,0.9556
196,196,B0028C44Z0,5,"Pros:<br />+packaging, shipping, price<br />+s...",-0.5656
197,197,B0028C44Z0,3,Be careful not to eat too many of them in one ...,0.4153
198,198,B0028C44Z0,5,These mints are really strong and have a great...,0.8268
199,199,B0028C44Z0,5,This is a huge supply of them. I'm still worki...,0.7178